apiVersion: v1
kind: Namespace
metadata:
  name: devel
---
apiVersion: v1
kind: Namespace
metadata:
  name: test1
---
apiVersion: v1
kind: Namespace
metadata:
  name: master
---
apiVersion: v1
kind: Namespace
metadata:
  name: v-0-0-1

