apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.0.95
    path: "/mnt/docker"
