apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.0.105
    path: "/mnt/docker-registry"
